Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from importlib.metadata import version

print("torch version:", version("torch"))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mPackageNotFoundError[0m                      Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mimportlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetadata[39;00m [38;5;28;01mimport[39;00m version
[0;32m----> 3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mtorch version:[39m[38;5;124m"[39m, [43mversion[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mtorch[39;49m[38;5;124;43m"[39;49m[43m)[49m)

File [0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/importlib/metadata.py:569[0m, in [0;36mversion[0;34m(distribution_name)[0m
[1;32m    562[0m [38;5;28;01mdef[39;00m [38;5;21mversion[39m(distribution_name):
[1;32m    563[0m [38;5;250m    [39m[38;5;124;03m"""Get the version string for the named package.[39;00m
[1;32m    564[0m 
[1;32m    565[0m [38;5;124;03m    :param distribution_name: The name of the distribution package to query.[39;00m
[1;32m    566[0m [38;5;124;03m    :return: The version string for the package as defined in the package's[39;00m
[1;32m    567[0m [38;5;124;03m        "Version" metadata key.[39;00m
[1;32m    568[0m [38;5;124;03m    """[39;00m
[0;32m--> 569[0m     [38;5;28;01mreturn[39;00m [43mdistribution[49m[43m([49m[43mdistribution_name[49m[43m)[49m[38;5;241m.[39mversion

File [0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/importlib/metadata.py:542[0m, in [0;36mdistribution[0;34m(distribution_name)[0m
[1;32m    536[0m [38;5;28;01mdef[39;00m [38;5;21mdistribution[39m(distribution_name):
[1;32m    537[0m [38;5;250m    [39m[38;5;124;03m"""Get the ``Distribution`` instance for the named package.[39;00m
[1;32m    538[0m 
[1;32m    539[0m [38;5;124;03m    :param distribution_name: The name of the distribution package as a string.[39;00m
[1;32m    540[0m [38;5;124;03m    :return: A ``Distribution`` instance (or subclass thereof).[39;00m
[1;32m    541[0m [38;5;124;03m    """[39;00m
[0;32m--> 542[0m     [38;5;28;01mreturn[39;00m [43mDistribution[49m[38;5;241;43m.[39;49m[43mfrom_name[49m[43m([49m[43mdistribution_name[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/importlib/metadata.py:196[0m, in [0;36mDistribution.from_name[0;34m(cls, name)[0m
[1;32m    194[0m         [38;5;28;01mreturn[39;00m dist
[1;32m    195[0m [38;5;28;01melse[39;00m:
[0;32m--> 196[0m     [38;5;28;01mraise[39;00m PackageNotFoundError(name)

[0;31mPackageNotFoundError[0m: torch

